### ISSUE TITLE
Track 'setClientWl' event trigger

### ISSUE THREAD

**Issue by TheMoose-GTW** [GTWCode/GTW-RPG#29]
It appears that one resource is still trigger this outdated event and thereby applies a wanted level causing errors in the server logs, I haven't figured out which one it is yet but all resources that does apply wanted level to players who commit crimes are upgraded to the new syntax and works. In game, this issue is known by not getting wanted in a situation you should be getting wanted in. Any ideas are welcome and a patch from anyone who may found it would be even more appreciated.

**Comment by TheWalrus-GTW** [comment]
Did a search in all project files and couldn't find that event anywhere, I have to close this now as it's not a GTW-RPG bug but related to our development server. I'll keep my eyes open tho, maybe I could use the same tool to search in the remaining server files.
