### ISSUE TITLE
How to configure the resources to start with the server

### ISSUE THREAD

**Issue by ghost** [GTWCode/GTW-RPG#3]
I never understood how the MOD to run

**Comment by smile68** [comment]
mtaserver 
<resource src="?" startup="1" protected="0" /

**Comment by MrBrutus-GTW** [comment]
Assuming you have the Multi Theft Auto server software available there are two ways to start the mod, first you need to copy all the folders into mods/deathmatch/resources/ (from server root), then you start the server. (Use /refresh if it's already running). And then "/start NameOfResource". What you have there is the file "mtaserver.conf" in mods/deathmatch/ allowing you to set up which resources should start together with the server.

All you need to add in the src property is the name of the resources you would like to start, that reminds me that we should make an installation guide as it takes some time writing all those config lines for this whole project. For now you may use this:

`    
    <resource src="GTWgui" startup="1" protected="1" />

    
    <resource src="GTWantispam" startup="1" protected="0" />
    <resource src="GTWchat" startup="1" protected="0" />
    <resource src="GTWfarmer" startup="1" protected="0" />
    <resource src="GTWfastfood" startup="1" protected="0" />
    <resource src="GTWfisher" startup="1" protected="0" />
    <resource src="GTWhelp" startup="1" protected="0" />
    <resource src="GTWmechanic" startup="1" protected="0" />
    <resource src="GTWphone" startup="1" protected="0" />
    <resource src="GTWplayerblips" startup="1" protected="0" />
    <resource src="GTWrob" startup="1" protected="0" />
    <resource src="GTWsmoke" startup="1" protected="0" />
    <resource src="GTWtrain" startup="1" protected="0" />
    <resource src="GTWtrainhorn" startup="1" protected="0" />
    <resource src="GTWturf" startup="1" protected="0" />
    <resource src="GTWturnsignals" startup="1" protected="0" />
    <resource src="GTWupdates" startup="1" protected="0" />
    <resource src="GTWvehicleshop" startup="1" protected="0" />
    <resource src="GTWweather" startup="1" protected="0" />`

Startup="1" force the resource to start together with the server and protected="1" prevent you from stopping the resource. Hope that helped you.

**Comment by smile68** [comment]
Thank you

**Comment by smile68** [comment]
only the strange black screen

**Comment by smile68** [comment]
maps where to put?

**Comment by MrBrutus-GTW** [comment]
Maps works like resources, just keep the project file tree structure from this page.

**Comment by TheWalrus-GTW** [comment]
Please use a proper and informative title that may help others with the same issue. I'm leaving this open now for further questions.

**Comment by TheMoose-GTW** [comment]
Information has been added in the file _Installation.md_ in main, consider this as resolved.
