### ISSUE TITLE
Merging it with other mods

### ISSUE THREAD

**Issue by AlphabetoPT** [GTWCode/GTW-RPG#36]
Hello sir, 
Probably you dont remember me but we chatted a little, about 3 months ago, about merging some features with socialz rp mod.
I am wondering if you are still available in providing support doing this. 
Better than that i am looking forward for an associate that can help me with the scripting.
I am new to lua and my knowledge is weak.
I wish to divide the profits of the server, if any, with you in a fair percentage of the income.
I compromise in invest alone in the machine needed for the server and in maintain ingame peace and order with my staff.
All i need for you is your expertise in scripting solving bugs that should appear mostly during the initial phase of the server's programming.

I hope to hear from you soon.
If you prefer contact me by email so we can chat a little about this matter.

Best Regards,
Diogo.
email. zionpt.mine at gmail dot com

**Comment by TheMoose-GTW** [comment]
That has never been done before but you could always try if you want, support for that are provided here: http://forum.404rq.com/programming-and-software/ as it's not directly related to GTW-RPG.
