### ISSUE TITLE
Cant Run it

### ISSUE THREAD

**Issue by AlphabetoPT** [GTWCode/GTW-RPG#4]
Hello.
I am new to Lua and as so i am trying to get some scripts together in order to make ''my game style''
I have searched a lot on MTA community forums and everyone says your scripts are good.
Following that path i downloaded your project GTW-RPG in order to try it to check if i can use some of the scripts contained in this GM. Such as Job Script.

I copied all files to a folder to /deathmatch/resources and i changed mtaserver.conf in order to startup from this package. I cant get it to run.
Help please.
When i do refresh it says it cannot find meta for this resource.
Do i have to place it individually and add 1 by 1 to the metaserver.conf?

thanks in advance

**Comment by MrBrutus-GTW** [comment]
Actually there's a file in the resources folder of the MTA server itself called "folderlayout.txt" have a look at that. What it says is basically that a folder is considered as a resource, but a folder surrounded by square brackets is considered as a folder. So what you have to do is to copy the files from /resources of this project into your resources folder in your MTA server.

All resources (folders with a file named "meta.xml" in it) has to be listed in the file: "mtaserver.conf" as well. This is because it isn't an official game mode yet, more of standalone resources. On our own servers we have the project on a different location using a shell script to copy the files to any local server available as we run multiple servers.

We are working on a solution for that however, like rename "resources" and "maps" to "[resources]" and "[maps]" respectively, then publishing the part of the config file as well. But until then the above described way is the only way if you wish to run all resources. I also recomend you to have a look at this: https://wiki.multitheftauto.com/wiki/Resources if you haven't done it yet. Good luck :)

**Comment by AlphabetoPT** [comment]
Good morning sir. Understood.
I will start one resource at a time with it required dependencies if it is
The case. I started fastfood and topbar and yep its working however The
menu is allways opened even outside The restaurants and its not creating
peds inside the restaurants as i think it should. Am i doing something
wrong?

Regards

**Comment by MrBrutus-GTW** [comment]
Peds are handled by GTWrob and to make the GUI work properly you need to load GTWgui before anything else. That and the topbar should alway be loaded before anything else.

**Comment by AlphabetoPT** [comment]
Thanks once again. GUI working good now.
However restaurants are not created. only show blips at map & radar.
i followed your directions. what am i doing wrong?

**Comment by MrBrutus-GTW** [comment]
You need the default resource interiors. Type "/start interiors" and enjoy.

**Comment by AlphabetoPT** [comment]
I am using other interiors from fairplay-roleplay. it will bug. wont it?

**Comment by AlphabetoPT** [comment]
Done! I was able to merge the interiors.
i just deleted everyone except Restaurants from interiors (resource) -> interiors.map.

However i still got a question for you my friend.
is there any simple way to change the prices or just by reediting your script?
I managed to find the prices on the script however they appear lots of times during the script and i am afraid i'll break the code.

I think they are too cheap. 

Thanks in advance.
And really GOOD job on this scripts.

Question Number 2 i read somewhere about your job plugin.
Is it complete? 
can you spare me the link?

Have a nice day bro

**Comment by TheWalrus-GTW** [comment]
Check the file data.lua, line 159 and 163. There are two tables there named prices and health, those basically contains a list with 4 items each informing any restaurant, no matter what menu they got how much it will cost and how much the health will go up.

On question number 2 I recommend you to read the documentation: https://github.com/GTWCode/GTW-RPG/tree/master/resources/GTWcivilians, it clearly says that the job system only manage the jobs by setting team and occupations. There is a rental/job vehicle system under construction on our development servers which hasn't been included here yet but that one manage all the vehicles for any job obviously. 

The actual missions during the jobs are located in individual resources, not yet published either, except for farmer and fisher as those require people to use their own vehicle which can be provided by GTWvehicleshops. Try those for a preview in how it works or visit our public development server: mtasa://s4.albonius.com:22005

**Comment by AlphabetoPT** [comment]
Thank you very much sir.
I will keep your scripts under sight.
I am merging some of your scripts with Fairplay - RPG available here on GitHub.
Hope you dont mind.

I am amateur coder, new to Lua. Still cant script anything on my own :)
I will in the future **Hope**

Cheers

**Comment by guilherme15s** [comment]
Hello good evening, I came here to say you're doing a great job making scripts on that level and releasing them, wanted to report a bug with the mod of the mechanical grip when '' X '' he does not open his gui by clicking the car can not messing in other resources with the cursor. It would be a bug or installed wrong?
Sorry for bad english =D

**Comment by MrBrutus-GTW** [comment]
guilherme15s. Did you start the following resources?
GTWgui
GTWmechanic

**Comment by TheWalrus-GTW** [comment]
AlphabetoPT, Feel free to keep us updated with your work regarding the merging of GTW-RPG with fairplay. If it's possible without to much work we might take a look at some kind of official support for that.

**Comment by guilherme15s** [comment]
Actually I was doing something wrong, I stopped all my resources and I left running and only they worked perfectly. Thanks anyway
Got a tip for police work, which is like the mechanic who is following the officer presses a button and click on the player to see the type of crime he committed or that type of infringement he made with the car.
