### ISSUE TITLE
Black screen when I join the server?

### ISSUE THREAD

**Issue by peppinoita** [GTWCode/GTW-RPG#6]
Hi guys, thanks for your job!
I like very much your mod, and I'm taking some time to test a little server on my pc (just for fun).

I set up everything (or al leas I guess) but when I join the server the only thing I get is a black screen.
Is there something I am missing?

Thanks again

**Comment by TheMoose-GTW** [comment]
There is no spawn manager built in currently, GTWaccounts is the name of the missing resource and will be included as soon as possible but until then you'll have to use something else like freeroam "play" or maybe "spawnmanager" (default resources). To spawn the player into the game and fade the camera in. When that is setup, all features will work as they should.

You may add the below code, meanwhile.
```lua
function onJoin(plr)
    outputChatBox("Please login by using /login <name> <password> or register with /register <name> <password>", plr)
end
addEventHandler("onPlayerJoin", onJoin)

function onLogin(acc)
    fadeCamera(source)
    spawnPlayer(source, 0, 0, 5)
    setPlayerTeam(source, "Unemployed")
    setCameraTarget(source, source)
end
addEventHandler("onPlayerLogin", onLogin)
```

None of above is tested, check the syntax on MTA wiki if it doesn't work. It's just a temporary solution and our account system will be available in this package in a few days hopefully.

**Comment by TheWalrus-GTW** [comment]
Spawn on login is not in GTWaccounts, however, GTWaccounts provide the actual login GUI and some other useful helper functions. GTWaccounts is now available but the spawn function is still required. We're working on it, try it out and see if it's any difference.

**Comment by TheMoose-GTW** [comment]
GTWcore are in charge of the spawn as well as saving and loading user data, this must be fixed soon as it's confusing for people using these resources as a game mode. It's currently a pack of standalone resources more than a full and working game mode. As @TheWalrus-GTW says, it should work by adding the spawn function to "onPlayerLogin" at GTWaccounts and start it. 

"Black screen" occurs on all MTA servers if there is no gamemode with a built in spawn manager running on them. A popular solution is to use freeroam together with GTW-RPG resources, to do so, simply use this command:

`start play`
And join the server.

**Comment by ThePenguin-GTW** [comment]
Try to use a more informative title, there has been more people asking about this. Thank you.
