### ISSUE TITLE
No vehicles or missions blips after job selection

### ISSUE THREAD

**Issue by peppinoita** [GTWCode/GTW-RPG#7]
Hello guys.
Sorry for boring you again.
If I go on a job marker I get the skin/weapon chooser window.
After I made my choose, I find myself with the job skin but nothing more.
Should I have the job vehicle and the mission blip on the radar?

**Comment by ThePenguin-GTW** [comment]
Once again, GTW-RPG is a pack of resources that provides features to a server, it's not an exact copy of the Grand Theft Walrus game servers even if those are based on GTW-RPG. The actual jobs except for farmer and fisher are not yet included. GTWcivilians is a job management system which assign a job to a player, each job has it's own resource and vehicles are provided by GTWvehicles which is not yet available.

**Comment by TheMoose-GTW** [comment]
As the discussion goes we've now started on v3.0, the version that will convert GTW-RPG into a full game mode, and exact copy of the live server basically. To do so we'll include our modified versions of third party resources into this project and the remaining GTW resources that isn't available here yet. This includes the rental vehicle system which is soon ready for release. Right now the account system is a little bit more important.

**Comment by TheWalrus-GTW** [comment]
Resources that isn't licensed as GPL yet is not an issue, our server runs third party resources as well which you won't find in the GTW-RPG project, at least not for now, vehicle shops and player owned vehicles are available so far, rental vehicles comes soon and "parked vehicles" is planned. If you have suggestions or wanna discuss development, do it here: http://forum.gtw-games.org/mta-servers-development/
